name: Run AI Trading Bot

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run trading bot
        run: |
          if [ ! -f "model.pkl" ]; then
            echo "Model not found! Skipping trading."
            exit 0
          fi
          python main.py

      - name: Commit updated balance and portfolio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add balance.txt portfolio.json
          git commit -m "Update portfolio after bot run" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
