name: Run AI Trading Bot

on:
  schedule:
    - cron: "0 * * * *"   # Every hour
  workflow_dispatch:       # Manual trigger

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run trading bot script
        run: python main.py

      - name: List files for debug
        run: ls -l

      - name: Commit updated portfolio and balance files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if test -f balance.txt; then git add balance.txt; fi
          if test -f portfolio.json; then git add portfolio.json; fi
          git commit -m "Update portfolio after bot run" || echo "No changes to commit"
          git push
