name: Train AI Models

on:
  workflow_dispatch:       # Run manually from GitHub UI
  schedule:
    - cron: "0 0 * * *"   # Every day at midnight UTC

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run model training script
        run: python train_model.py
