name: Train AI Model

on:
  workflow_dispatch:    # lets you run it manually from GitHub UI
  schedule:
    - cron: '0 0 * * 0'  # runs weekly on Sunday at midnight (adjust if needed)

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run training script
      run: python train_model.py
