name: Train AI Models

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # every day at 3 AM UTC

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python train_model.py

      - name: Configure Git
        run: git config user.name "github-actions[bot]" && git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit trained models if they exist
        env:
          PAT_TOKEN: ${{ secrets.Ai-trader }}
        run: |
          if [ -d "models" ]; then \
            git add models/ && \
            if ! git diff --cached --quiet; then \
              git commit -m "Save trained models" && \
              git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main; \
            else \
              echo "No model changes to commit."; \
            fi; \
          else \
            echo "No models directory found, skipping commit."; \
          fi
